name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Protobuf Library
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
    - name: make
      run: pwd && ls include && ls include/onnx/ && make
    - name: make run
      run: make run-mobilenet
